name: air_quality_prediction
services:
  streamlit:
    build: 
      context: .
      dockerfile: ./docker/streamlit/Dockerfile
    image: argamarihot/ml_process_streamlit
    container_name: streamlit_frontend
    depends_on:
      - api
    ports:
      - 8501:8501 #host:container

  api:
    build: 
      context: .
      dockerfile: ./docker/api/Dockerfile
    image: argamarihot/ml_process_api
    container_name: api_backend
    ports:
      - 8080:8080
